
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhtxzdpdcnbwjirpccbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhodHh6ZHBkY25id2ppcnBjY2JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NzUxNDQsImV4cCI6MjA2MzI1MTE0NH0.fDnq_MbkiSydcTsj-EA5PV5JCoBpEV7TmIbvF9WhRIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
